In [0]:
# https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/Part%201%20-%20Tensors%20in%20PyTorch%20(Exercises).ipynb
import torch 

torch.manual_seed(7)
features = torch.randn((1, 3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn((n_input, n_hidden))
W2 = torch.randn((n_hidden, n_output))

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


In [24]:
def sigmoid(s):
  return 1/(1+torch.exp(-s))


print(f'features:\n {features}')
print('---------')
print(f'W1:\n{W1}')
print('---------')
print(f'W2:\n{W2}')
print('---------')
print(f'B1:\n{B1}')
print('---------')
print(f'B2:\n{B2}')

# tmp = torch.dot(features, W1)

A0 = sigmoid(torch.matmul(features, W1) + B1)
A1 = sigmoid(torch.matmul(A0, W2) + B2)

print(A1)

features:
 tensor([[-0.1468,  0.7861,  0.9468]])
---------
W1:
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
---------
W2:
tensor([[-1.6822],
        [ 0.3177]])
---------
B1:
tensor([[0.1328, 0.1373]])
---------
B2:
tensor([[0.2405]])
tensor([[0.3171]])
