In [1]:
#Building fully-connected neural networks with PyTorch
from google.colab import drive
drive.mount("/content/gdrive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
%matplotlib inline 
%config InlineBackend.figure_format = 'retina'
import numpy as np 
import torch 
import helper 
from matplotlib import pyplot as plt 
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, ), (0.5, )), ])
trainset = datasets.MNIST('MNIST/train', train=True, download=True, transform=transform)
training_data = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = datasets.MNIST('MNIST/test', train=False, download=True, transform=transform)
testing_data = torch.utils.data.DataLoader(testset, batch_size=64)


0it [00:00, ?it/s]

9920512it [00:02, 3639099.60it/s]                             


Extracting MNIST/train/MNIST/raw/train-images-idx3-ubyte.gz to MNIST/train/MNIST/raw


0it [00:00, ?it/s]

32768it [00:00, 57874.83it/s]                           
0it [00:00, ?it/s]

Extracting MNIST/train/MNIST/raw/train-labels-idx1-ubyte.gz to MNIST/train/MNIST/raw


1654784it [00:01, 950616.15it/s]                             
0it [00:00, ?it/s]

Extracting MNIST/train/MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST/train/MNIST/raw


8192it [00:00, 21591.31it/s]            
0it [00:00, ?it/s]

Extracting MNIST/train/MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST/train/MNIST/raw
Processing...
Done!


9920512it [00:02, 4317246.48it/s]                            


Extracting MNIST/test/MNIST/raw/train-images-idx3-ubyte.gz to MNIST/test/MNIST/raw


0it [00:00, ?it/s]

32768it [00:00, 57190.72it/s]                           
0it [00:00, ?it/s]

Extracting MNIST/test/MNIST/raw/train-labels-idx1-ubyte.gz to MNIST/test/MNIST/raw


1654784it [00:01, 953449.51it/s]                             
0it [00:00, ?it/s]

Extracting MNIST/test/MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST/test/MNIST/raw


8192it [00:00, 21777.93it/s]            

Extracting MNIST/test/MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST/test/MNIST/raw
Processing...
Done!


In [3]:
dataiter = iter(training_data)
images, labels = dataiter.next()
print(type(images))
print(images.shape)
print(labels.shape)



<class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64])


In [0]:
import torch.nn as nn 
import torch.nn.functional as F
class Net1(nn.Module):
  def __init__(self):
    super().__init__()

    self.hidden = nn.Linear(784, 256)
    self.output = nn.Linear(256, 10)

    self.sigmoid = nn.Sigmoid()
    self.softmax = nn.Softmax(dim = 1)

  def forward(self, x):

    x = self.hidden(x)
    x = self.sigmoid(x)
    x = self.output(x)
    x = self.softmax(x)

    return x
  
net1 = Net1()

In [0]:
import torch.nn as nn 
import torch.nn.functional as F

class Net2(nn.Module):

  def __init__(self):
    super().__init__()

    self.hidden = nn.Linear(784, 256)
    self.output = nn.Linear(256, 10)

  def forward(self, x):

    x = torch.sigmoid(self.hidden(x))
    x = F.softmax(self.output(x), dim=1)

    return x
  
net2 = Net2()

In [6]:
x = torch.randn((1, 784))
out1 = net1(x)
out2 = net2(x)
print(out1)
print(out2)

tensor([[0.0814, 0.0898, 0.1029, 0.0791, 0.0766, 0.1808, 0.1018, 0.0676, 0.1248,
         0.0951]], grad_fn=<SoftmaxBackward>)
tensor([[0.0847, 0.0917, 0.0777, 0.1413, 0.0766, 0.0579, 0.1366, 0.1148, 0.1276,
         0.0912]], grad_fn=<SoftmaxBackward>)


In [0]:
import torch.nn as nn 
import torch.nn.functional as F

class Net3(nn.Module):

  def __init__(self):
    super().__init__()
    self.hidden1 = nn.Linear(784, 128)
    self.hidden2 = nn.Linear(128, 64)
    self.output = nn.Linear(64, 10)

  def forward(self, x):
    
    x = F.relu(self.hidden1(x))
    x = F.relu(self.hidden2(x))
    x = self.output(x)
  
    return F.softmax(x, dim=1)

net3 = Net3()

In [44]:
# x = torch.randn((1, 784))
# print(x)
print(net1)
out1 = net1(x)
print(net2)
out2 = net2(x)
print(net3)
out3 = net3(x)
print(out1)
print(out2)
print(out3)


Net1(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
)
Net2(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)
Net3(
  (hidden1): Linear(in_features=784, out_features=128, bias=True)
  (hidden2): Linear(in_features=128, out_features=64, bias=True)
  (output): Linear(in_features=64, out_features=10, bias=True)
)
tensor([[0.0924, 0.0933, 0.1066, 0.0730, 0.0832, 0.1708, 0.1009, 0.0545, 0.1317,
         0.0936]], grad_fn=<SoftmaxBackward>)
tensor([[0.0773, 0.0982, 0.0742, 0.1282, 0.0873, 0.0763, 0.1126, 0.1195, 0.1281,
         0.0984]], grad_fn=<SoftmaxBackward>)
tensor([[0.1055, 0.0866, 0.1224, 0.0843, 0.1049, 0.0792, 0.0989, 0.0858, 0.1149,
         0.1175]], grad_fn=<SoftmaxBackward>)


In [50]:
print(net3.hidden1.weight)
print(net3.hidden1.bias)

#Set biases to all zero
net3.hidden1.bias.data.fill_(0)

#Simple from random normal with standard dev = 0.01
net3.hidden1.weight.data.normal_(std=0.01)

print(net3.hidden1.weight)
print(net3.hidden1.bias)

Parameter containing:
tensor([[ 0.0295,  0.0094, -0.0011,  ..., -0.0180, -0.0007, -0.0245],
        [-0.0078,  0.0042, -0.0211,  ..., -0.0018, -0.0093, -0.0344],
        [ 0.0166, -0.0253, -0.0064,  ..., -0.0119, -0.0018,  0.0039],
        ...,
        [-0.0220, -0.0105,  0.0258,  ...,  0.0333,  0.0283, -0.0287],
        [ 0.0057,  0.0073,  0.0102,  ..., -0.0227, -0.0259, -0.0349],
        [-0.0298, -0.0212, -0.0025,  ...,  0.0322,  0.0094,  0.0058]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0036, -0.0095, -0.0074,  0.0025, -0.0047, -0.0164,  0.0027, -0.0122,
         0.0088, -0.0202, -0.0018, -0.0104,  0.0095, -0.0104,  0.0049,  0.0095,
        -0.0199, -0.0043,  0.0008,  0.0099,  0.0195, -0.0131, -0.0111,  0.0133,
         0.0179, -0.0189,  0.0017, -0.0053, -0.0038, -0.0138,  0.0135, -0.0091,
         0.0099,  0.0042,  0.0114, -0.0085,  0.0179, -0.0124, -0.0036, -0.0127,
        -0.0005,  0.0071,  0.0072,  0.0089,  0.0064,  0.0093, -0.0098, -0.0192,
        -0.0035

In [0]:
#Grab some data 
dataiter = iter(training_data)
images, labels = dataiter.next()

img_idx = 0
images = images.view(-1, 1, 784)

out = net3.forward(images[img_idx, :])

img = images[img_idx, :]
# !pip install helper

In [74]:
input_size = 784 
hidden_size = [128, 64]
output_size = 10

model = nn.Sequential(nn.Linear(input_size, hidden_size[0]),
                         nn.ReLU(),
                         nn.Linear(hidden_size[0], hidden_size[1]),
                         nn.ReLU(),
                         nn.Linear(hidden_size[1], output_size),
                         nn.Softmax(dim=1))
print(model)
print(model[0])

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): Softmax(dim=1)
)
Linear(in_features=784, out_features=128, bias=True)


In [72]:
from collections import OrderedDict
input_size = 784 
hidden_size = [128, 64]
output_size = 10

model = nn.Sequential(OrderedDict([('fc1', nn.Linear(input_size, hidden_size[0])),
                         ('relu1', nn.ReLU()),
                         ('fc2', nn.Linear(hidden_size[0], hidden_size[1])),
                         ('relu2', nn.ReLU()),
                         ('output', nn.Linear(hidden_size[1], output_size)),
                         ('softmax', nn.Softmax(dim=1))]))
print(model)
print(model[0])
print(model.fc1)

Sequential(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (output): Linear(in_features=64, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)
Linear(in_features=784, out_features=128, bias=True)
Linear(in_features=784, out_features=128, bias=True)
